name: Build iOS IPA

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Resolve Swift Packages
        run: swift package resolve

      - name: Build and Archive IPA
        run: |
          xcodebuild \
            -scheme App \
            -destination "generic/platform=iOS" \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $PWD/build

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: FindMyFriends-IPA
          path: build/*.ipa